# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

conda:
  environment: build-doc.yml

# Optionally build your docs in additional formats such as PDF and ePub
formats: all

# Optionally set the version of Python and requirements required to build your docs
build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-4.10"
  jobs:
    pre_install:
      - EXTRA_CMAKE_ARGS="-DCMAKE_PREFIX_PATH=${CONDA_PREFIX} -DCMAKE_INSTALL_PREFIX=${CONDA_PREFIX}" ./scripts/build_libleidenalg.sh

python:
  install:
    - method: pip
      path: .

submodules:
  include: all
  recursive: true

# Build documentation in the doc/source directory with Sphinx
sphinx:
  configuration: doc/source/conf.py